import assert from 'node:assert/strict';
import fs from 'node:fs';
import {compileConnectedCoverWorld} from './engine/world/connected-cover-world.js';
import {traceRegionSight} from './engine/world/region-sight.js';
import {moveRegionProbe} from './engine/world/region-motion.js';
const doc=JSON.parse(fs.readFileSync('levels/fixtures/connected-global.nil.json'));
const world=compileConnectedCoverWorld(doc),start=world.spawn();
const sight=traceRegionSight(world,{regionId:start.regionId,position:start.position,direction:start.camera.forward},{maxDistance:60});
assert.equal(sight.status,'hit',JSON.stringify(sight));assert.equal(sight.query.owner,'flat-target');
assert.equal(sight.crossings.length,2);assert.ok(Math.abs(sight.distance-(2+1.5*Math.PI*8+2.4))<1e-8);
assert.ok(sight.segments.some(s=>s.regionId==='sphere'&&s.distance>Math.PI*8));
let state=start,visited=['flat'],antipode=false;
for(let i=0;i<140;i++){
  const result=moveRegionProbe(world,{...state,velocity:state.camera.forward.map(x=>x*4)},.1);
  assert.ok(['complete','stopped'].includes(result.status),`${result.status}/${result.detail}`);
  state=result.state;
  if(state.regionId!==visited.at(-1))visited.push(state.regionId);
  if(state.regionId==='sphere'&&state.position[3]<-.999)antipode=true;
  if(visited.length===3)break;
}
assert.deepEqual(visited,['flat','sphere','flat']);assert.ok(antipode,'body path must pass antipode');
assert.ok(state.position[0]>2.99,'return portal must determine the new position');
const reloaded=compileConnectedCoverWorld(JSON.parse(JSON.stringify(world.document())));
const again=traceRegionSight(reloaded,{regionId:start.regionId,position:start.position,direction:start.camera.forward},{maxDistance:60});
assert.equal(again.query.owner,sight.query.owner);assert.ok(Math.abs(again.distance-sight.distance)<1e-10);
assert.throws(()=>world.renderData(),/global-capable/);
const colliding=structuredClone(doc);
colliding.coverRegions[0].entities.push({id:'sphere-blocker',kind:'ball',chartId:'north-chart',position:[0,1.5,0],radius:.4});
const obstacle=compileConnectedCoverWorld(colliding);state=obstacle.spawn();
for(let i=0;i<25;i++)state=moveRegionProbe(obstacle,{...state,velocity:state.camera.forward.map(x=>x*4)},.1).state;
assert.equal(state.regionId,'sphere');
const region=obstacle.regions.get('sphere');
assert.ok(region.field.distance(state.position)-state.radius>=-1e-7,'global ball collision must keep physical clearance');
assert.ok(region.space.distance(region.space.origin,state.position)<.86,'must stop before blocker');
const malformed=structuredClone(doc);malformed.connections[0].extra=true;
assert.throws(()=>compileConnectedCoverWorld(malformed),/Invalid connection/);
doc.coverRegions[0].charts[0].center[3]=-1;
assert.equal(world.document().coverRegions[0].charts[0].center[3],1,'compiled world snapshots author data');
console.log('connected cover: E3/global-S3/E3 sight and body route, antipode, save/load, collision and refusal passed');
