// FLAT 3-MANIFOLDS: E^3 quotiented by a lattice.
//
// The fifth geometry, and the first one here that is deliberately BORING to
// look at. Everything else in this project exists because it does something a
// flat world cannot; this one exists to be the thing they are measured
// against, and it earns its place three times over:
//
// 1. IT IS THE ONLY WORLD WHERE A PORTED MAP IS THE MAP. `port.js` spends
//    seven hundred lines on the fact that there is no isometric embedding
//    between surfaces of different curvature, and every strategy in it trades
//    one exact property for two wrong ones. Port a flat floor plan into E^3
//    and there is nothing to trade: every length, every angle, every straight
//    wall, exactly. So the same plan can be built here and in H^3 and PLAYED
//    BACK TO BACK, which turns "what does curvature do to a level" from an
//    argument into a comparison. `E3T_PLAN` below is that plan, and
//    `tools/port-map.js` will carry it into either hyperbolic world.
//
// 2. IT IS THE EXACT STRUCTURAL MIRROR OF THE TWO HYPERBOLIC WORLDS. The
//    option is the same option:
//
//        floor (2D wrap)   H^3:  octagon -> genus-2 surface x R
//                          E^3:  square  -> 2-torus x R
//        open  (3D wrap)   H^3:  Seifert-Weber dodecahedral space
//                          E^3:  the 3-torus
//
//    and the square cell's inradius is 1.50 against the octagon's 1.5286, so
//    the two are very nearly the same size of room. Same level, same course,
//    same controls, one switch, and the only difference is the curvature.
//
// 3. THE 3-TORUS DOES A THING NO OTHER WORLD HERE CAN. See "gravity without a
//    height" below. It is the cleanest demonstration in the project of what
//    "the field must descend to the quotient" actually means.
//
// The geometry itself is `geom.js` at k = 0 and nothing else -- that is what
// geom.js is FOR, and this file is the payoff for having written it. What is
// local to here is the lattice, the level, and the walking.
//
// No DOM and no graphics, so it is testable.

import { geometry } from './geom.js';

// --- the geometry, which is geom.js at k = 0 ------------------------------
//
// Every primitive is one line. A point is (x, y, z, 1) -- the affine plane
// x3 = 1, which is what the k = 0 model degenerates to -- and a placement is
// an ordinary affine matrix [R | t ; 0 1], column-major like everything else.
// `geom.js` already special-cases the degenerate form in `normalize`, `inv`
// and `reorthonormalize`, so there is nothing to write here at all.

const E = geometry(0);

export const dot = E.dot;
export const ORIGIN = E.ORIGIN;
export const IDENTITY = E.IDENTITY;
export const matMul = E.matMul;
export const apply = E.apply;
export const point = E.point;
export const frameVec = E.frameVec;
export const fromFrame = E.fromFrame;
export const translation = E.translation;
export const translationBy = E.translationBy;
export const exp = E.exp;
export const log = E.log;
export const dist = E.dist;
export const geodesic = E.geodesic;
export const rayPoint = E.rayPoint;
export const reorthonormalize = E.reorthonormalize;
export const logTo = E.logTo;
export const inv = E.inv;
export const groupError = E.groupError;

/** A placement at (x, y, z) with the standard frame. Mirrors hyp.placeAt. */
export const placeAt = (x, y, z) => translation([x, y, z]);

// --- the lattice ----------------------------------------------------------
//
// A RECTANGULAR lattice, which is the whole group: Lambda is generated by
// three translations along the axes and every element is an integer
// combination of them. Compare hyp.js, where the octagon group needs eight
// 4x4 Lorentz matrices and the dodecahedral one needs twelve, and where
// reducing a point to the fundamental domain is a greedy search that takes
// about seven iterations of eight inner products.
//
// Here reduction is Math.round. That single fact is why this file has no
// `reduceToDomain`, why the shader has no fold loop, and why the whole
// "the renderer teleports; the physics folds" apparatus is absent -- see
// `torusDisp` below, which is the entire quotient.

/**
 * The cell, and the size is chosen rather than arbitrary.
 *
 * 3.0 along each axis makes the square cell's inradius 1.50, against the
 * octagon's 1.5286 and the dodecahedron's 0.996. So a level authored for the
 * bounded hyperbolic world very nearly fits here unchanged, which is the
 * point: the comparison is only honest if the rooms are the same size.
 *
 * The z entry is used only in the 3-torus. In the slab world the height is a
 * genuine Euclidean line, exactly as it is in both products.
 */
export const CELL = [3.0, 3.0, 3.0];

/** Half the cell: the inradius of the fundamental domain, per axis. */
export const HALF = CELL.map((c) => c / 2);

/** The two flat worlds, mirroring the two hyperbolic ones exactly. */
export const MODE = { SLAB: 'slab', CUBE: 'cube' };

/** Which axes are glued, per world. The height is the only difference. */
export const wrapsZ = (mode) => mode === MODE.CUBE;

/**
 * One coordinate, brought back into [-L/2, L/2).
 *
 * This is `reduceToDomain`, and it is one line. `Math.round` breaks ties to
 * even rather than away from zero, which does not matter: a point exactly on a
 * face is on both, and the two answers are the same point of the quotient.
 */
export const wrap1 = (d, L) => d - L * Math.round(d / L);

/**
 * The MINIMUM IMAGE displacement from q to p: the shortest of all the
 * representatives, componentwise.
 *
 * This is the whole quotient, and putting it here rather than in a fold step
 * is the design decision this world turns on.
 *
 * In H^3 the renderer never leaves the fundamental domain, because reduction
 * costs seven iterations of eight inner products and at 220 steps a pixel that
 * is not affordable -- CLAUDE.md says exactly that, and it is right there.
 * Here reduction costs three subtractions and three roundings, so the argument
 * flips and the SIMPLER strategy wins: fold every displacement, inside the
 * distance function, and then nothing else in the renderer or the physics has
 * to know there is a group at all. No fundamental domain, no face scan, no
 * exit solve, no fold loop, no straddle copies, no carried objects.
 *
 * EXACT, with one condition, and it is the condition the hyperbolic worlds
 * already impose in another spelling: the primitive must fit inside half a
 * cell along each glued axis. A sphere of radius r about a centre is exactly
 * right whenever r < L/2; a segment is exactly right whenever its half-length
 * plus its thickness is. That is the same "centre distance plus thickness must
 * stay under the inradius" clearance rule as level.js, restated flat, and
 * `e3t.test.js` checks the level against it rather than trusting it.
 */
export function torusDisp(p, q, mode) {
  const wz = wrapsZ(mode);
  return [
    wrap1(p[0] - q[0], CELL[0]),
    wrap1(p[1] - q[1], CELL[1]),
    wz ? wrap1(p[2] - q[2], CELL[2]) : p[2] - q[2],
  ];
}

/** Distance in the QUOTIENT: the shortest of all the ways round. */
export function torusDist(p, q, mode) {
  const d = torusDisp(p, q, mode);
  return Math.hypot(d[0], d[1], d[2]);
}

/** Horizontal distance in the quotient, ignoring height. */
export function torusHorizDist(p, q) {
  return Math.hypot(wrap1(p[0] - q[0], CELL[0]), wrap1(p[1] - q[1], CELL[1]));
}

/**
 * A point brought into the fundamental cell.
 *
 * Nothing in the renderer needs this -- `torusDisp` has already made every
 * distance a quotient distance, so a ray may run out into the covering space
 * for ever and still see the right world. It is here because the HUD wants a
 * bounded number to print and because the tests want a canonical
 * representative to compare against, which is the same reason
 * `reduceToDomain` is canonical in hyp.js.
 */
export function foldPoint(p, mode) {
  const d = torusDisp(p, [0, 0, 0, 1], mode);
  return [d[0], d[1], d[2], 1];
}

/** The lattice vector `foldPoint` took off. Mirrors hyp.foldElement. */
export function foldElement(p, mode) {
  const f = foldPoint(p, mode);
  return [p[0] - f[0], p[1] - f[1], p[2] - f[2]];
}

// --- closed geodesics, and they are DENSE ---------------------------------
//
// In the octagon world there are exactly eight closed geodesics through the
// cell centre, one per generator, all of length 2*OCT_R = 3.057, and every
// other direction never returns. In the dodecahedral world there are twelve.
// A closed hyperbolic manifold has a DISCRETE length spectrum with a shortest
// geodesic and finitely many below any bound: that rigidity is Mostow's
// theorem showing up as a fact about level design, and it is why the boomerang
// has a heuristic that picks one of eight axes rather than flying where it was
// aimed.
//
// A torus is the opposite in every respect. A direction closes if and only if
// it is RATIONAL in the lattice basis, so the closing directions are DENSE in
// the sphere of directions: aim anywhere and you are arbitrarily close to a
// direction that comes back. They come in continuous families too -- every
// parallel translate of a closed geodesic is closed and has the same length --
// where in a hyperbolic manifold each one is isolated and rigid.
//
// That is a real mechanic and not a curiosity. A boomerang thrown here comes
// back from very nearly any aim; what the aim buys you is HOW LONG IT TAKES,
// because the length of the (a,b,c) geodesic is |(a Lx, b Ly, c Lz)| and a
// complicated ratio is a long flight. Aim carelessly and it returns next week.

const gcd = (a, b) => (b ? gcd(b, a % b) : Math.abs(a));

/** The length of the closed geodesic in the primitive direction (a, b, c). */
export const closedLength = (a, b, c) =>
  Math.hypot(a * CELL[0], b * CELL[1], c * CELL[2]);

/**
 * Every primitive closing direction with coefficients up to `n`, shortest
 * first.
 *
 * Primitive means gcd 1: (2,2,0) is the (1,1,0) geodesic run twice, not a new
 * one. In the slab world c must be 0, because the height is not glued and a
 * geodesic with any vertical component simply leaves.
 */
export function closedDirs(mode = MODE.SLAB, n = 3) {
  const out = [];
  const cMax = wrapsZ(mode) ? n : 0;
  for (let a = -n; a <= n; a++) {
    for (let b = -n; b <= n; b++) {
      for (let c = -cMax; c <= cMax; c++) {
        if (!a && !b && !c) continue;
        if (gcd(gcd(a, b), c) !== 1) continue;
        const len = closedLength(a, b, c);
        const v = [a * CELL[0], b * CELL[1], c * CELL[2]];
        out.push({ n: [a, b, c], len, dir: v.map((x) => x / len) });
      }
    }
  }
  return out.sort((x, y) => x.len - y.len);
}

/**
 * The closing direction nearest an aim, and how far off it is.
 *
 * The boomerang's problem, and note how differently it reads from the
 * hyperbolic one: there the heuristic is choosing between eight fixed axes and
 * is usually a long way from the aim, and here it is a rational approximation
 * problem where a better answer always exists a little further out. `cost`
 * trades the angular error against the flight length, because a perfect aim
 * that takes forty seconds to come back is not the answer anyone wanted.
 */
export function nearestClosedDir(aim, mode = MODE.SLAB, n = 4) {
  let best = null;
  for (const g of closedDirs(mode, n)) {
    const c = aim[0] * g.dir[0] + aim[1] * g.dir[1] + aim[2] * g.dir[2];
    const ang = Math.acos(Math.max(-1, Math.min(1, c)));
    const cost = ang + 0.05 * g.len;
    if (!best || cost < best.cost) best = { ...g, ang, cost };
  }
  return best;
}

// --- the level, from a FLAT FLOOR PLAN ------------------------------------
//
// Authored as line segments in ordinary flat coordinates, because that is what
// a floor plan IS and because it is exactly the input `tools/port-map.js`
// takes. Built here it is exact; ported into H^3 it is not, and the difference
// between those two is the entire subject of port.js.
//
// Read the coordinates as a Euclidean grid, and note that this is the ONE
// world in this project where that sentence is true -- level.js says in
// capitals that its (a, b) are geodesic polar and that two positions are not
// |da, db| apart. Here they are. That is the whole content of "flat".

export const WALL_T = 0.12;         // half-thickness
export const WALL_H = 1.80;         // taller than the player, short of the roof
export const CEIL_Z = CELL[2];      // the roof IS the cell height, deliberately

/**
 * The plan. Segments, in metres, in the cell [-1.5, 1.5]^2.
 *
 * Two things about it are chosen rather than drawn:
 *
 * THE CENTRELINE y = 0 IS KEPT CLEAR ALL THE WAY ACROSS, and that corridor
 * joins its own image at x = +-1.5 into a street with no end. Look down it and
 * you see an infinite line of copies of yourself -- and in FLAT space they
 * recede like 1/d, so you see a dozen of them. In either hyperbolic world the
 * same sightline is killed by e^{2r} and the second copy is already a speck.
 * That contrast is the cheapest and clearest thing this world has to show, and
 * it costs one straight corridor.
 *
 * THE TWO DOORWAYS ARE OFFSET from each other, so the back alley -- the strip
 * from y = 1.05 out to the face at 1.5, which joins the strip from -1.5 to
 * -1.05 and is therefore also endless -- cannot be seen into from the street.
 * That second corridor exists ONLY because of the wrap: there is no wall at
 * y = +-1.5, there is no y = +-1.5.
 */
export const E3T_PLAN = [
  // The street's two walls, each with one doorway, the doorways offset.
  [[-1.50, 1.05], [0.35, 1.05]],
  [[0.95, 1.05], [1.50, 1.05]],
  [[-1.50, -1.05], [-0.55, -1.05]],
  [[0.05, -1.05], [1.50, -1.05]],
  // Two stubs in the alley, so it is a place rather than a gap.
  [[-0.60, 1.05], [-0.60, 1.50]],
  [[0.70, -1.50], [0.70, -1.05]],
];

/** A wall of the plan, as the data the SDF and the emitter both read. */
const wallOf = ([a, b]) => {
  const mid = [(a[0] + b[0]) / 2, (a[1] + b[1]) / 2];
  const ext = [(b[0] - a[0]) / 2, (b[1] - a[1]) / 2];
  return { mid, ext, half: Math.hypot(ext[0], ext[1]), top: WALL_H, mat: 3 };
};

export const E3T_WALLS = E3T_PLAN.map(wallOf);

/**
 * Pillars in the street, all of them off the centreline so the endless
 * sightline stays open. The tall pair reach the roof.
 */
export const E3T_PILLARS = [
  { c: [-1.00, 0.62], r: 0.18, top: CEIL_Z, mat: 4 },
  { c: [0.30, -0.58], r: 0.18, top: CEIL_Z, mat: 4 },
  { c: [1.10, 0.66], r: 0.22, top: 1.10, mat: 5 },
  { c: [-0.20, -0.80], r: 0.15, top: 1.40, mat: 5 },
];

/**
 * THE 3-TORUS SCAFFOLD, and it is the flat cousin of the dodecahedron's
 * spokes.
 *
 * A rod along x at fixed (y, z) meets the faces x = +-1.5 head on, and the
 * gluing there is the identity translation, so it joins its own image exactly:
 * one rod is an infinite straight rod, through every copy of the room, for
 * ever. Three families along the three axes, and they pass through each other
 * without meeting, which is the thing to look at -- a rod along x and a rod
 * along y at different heights are two infinite lines that never intersect and
 * are not parallel, which in a simply connected flat space is impossible for
 * lines through a bounded region.
 *
 * The hyperbolic spokes need a page of argument about the 3/10 turn lining a
 * spoke up with its neighbour's. Here it is a translation and there is nothing
 * to check, which is precisely the difference this world is here to show.
 */
// The offsets are SEARCHED for, not written down, exactly as the opponent
// spawn and the grapple ring were -- and the search decided the COURSE too,
// which was not the plan. A rod is an infinite line and the course is a closed
// geodesic wrapping several cells, so a carelessly placed rod meets it
// somewhere, and how much room there is to avoid one depends entirely on which
// closed geodesic the course flies. Sweeping the offset grid against the whole
// course line, for every direction worth using:
//
//     (1,0,0)  len 3.00   best rod clearance 1.400
//     (1,1,0)  len 4.24                      0.961
//     (1,1,1)  len 5.20                      0.961  on ALL THREE axes
//     (2,1,0)  len 6.71                      0.571
//     (2,1,1)  len 7.35                      0.571
//     (3,1,1)  len 9.95                      0.374
//
// (2,1,1) was the first choice, for being the more elaborate wrap. It leaves
// 0.571 against a gate radius of 0.55, so a rod misses a gate's rim by 0.021
// and the scaffold has to be built around the race track. (1,1,1) wraps once
// in each axis, is shorter, is far easier to say -- fly down the cell diagonal
// and you are back after L*sqrt(3) -- and leaves 0.961, which is 0.41 of
// genuine margin. `e3t.test.js` asserts the margin rather than trusting it.
export const E3T_RODS = [
  { axis: 0, at: [-1.00, 0.50], r: 0.10, mat: 6 },
  { axis: 0, at: [0.50, -1.00], r: 0.08, mat: 6 },
  { axis: 1, at: [-1.00, 0.50], r: 0.10, mat: 7 },
  { axis: 1, at: [0.50, -1.00], r: 0.08, mat: 7 },
  { axis: 2, at: [-1.00, 0.50], r: 0.10, mat: 8 },
  { axis: 2, at: [0.50, -1.00], r: 0.08, mat: 8 },
];

/** 2D distance from a wrapped offset to the wall's centre segment. */
function segDist(d, ext) {
  const ee = ext[0] * ext[0] + ext[1] * ext[1];
  const h = ee > 0 ? Math.max(-1, Math.min(1, (d[0] * ext[0] + d[1] * ext[1]) / ee)) : 0;
  return Math.hypot(d[0] - ext[0] * h, d[1] - ext[1] * h);
}

/**
 * The world as a distance and a material, exactly as `levelMap` is.
 *
 * Every term is exact rather than an underestimate, for the same reason the
 * products' are: flat distance is Pythagoras and nothing cancels. The `max`
 * that caps a column by its height is the usual convention -- exact inside,
 * an underestimate outside the rim, which is the safe direction.
 *
 * The QUOTIENT is entirely inside `wrap1`, called once per primitive on the
 * displacement. There is no fold, no straddle copy and no second pass over the
 * neighbours: level.js needs those because `reduceToDomain` gives one
 * representative and the nearest content may be across a face, and the minimum
 * image gives the nearest one directly.
 */
export function e3tMap(p, mode = MODE.SLAB) {
  if (wrapsZ(mode)) {
    // The 3-torus: RODS ONLY. Not a saving -- the walls and the pillars are
    // meaningless here. A wall with no roof to stop at is an infinite vertical
    // slab, and one of them stands across the closed geodesic the course flies
    // down. level.js splits its content the same way and for the same reason:
    // WALLS and TOWERS are octagon-only, SPOKES and PODS dodecahedron-only.
    let best = Infinity, mat = 6;
    for (const r of E3T_RODS) {
      // The two axes the rod does NOT run along; the one it does drops out
      // entirely, which is what makes it infinite.
      const [i, j] = r.axis === 0 ? [1, 2] : r.axis === 1 ? [0, 2] : [0, 1];
      const s = Math.hypot(wrap1(p[i] - r.at[0], CELL[i]),
                           wrap1(p[j] - r.at[1], CELL[j])) - r.r;
      if (s < best) { best = s; mat = r.mat; }
    }
    return [best, mat];
  }
  let best = p[2], mat = 1;                              // the floor, exact
  const ceil = CEIL_Z - p[2];
  if (ceil < best) { best = ceil; mat = 2; }
  for (const w of E3T_WALLS) {
    const d = [wrap1(p[0] - w.mid[0], CELL[0]), wrap1(p[1] - w.mid[1], CELL[1])];
    const s = Math.max(segDist(d, w.ext) - WALL_T, p[2] - w.top);
    if (s < best) { best = s; mat = w.mat; }
  }
  for (const c of E3T_PILLARS) {
    const dx = wrap1(p[0] - c.c[0], CELL[0]), dy = wrap1(p[1] - c.c[1], CELL[1]);
    const s = Math.max(Math.hypot(dx, dy) - c.r, p[2] - c.top);
    if (s < best) { best = s; mat = c.mat; }
  }
  return [best, mat];
}

/** Just the distance. */
export const e3tSDF = (p, mode = MODE.SLAB) => e3tMap(p, mode)[0];

/** The slab world's SDF, in the one-argument shape the physics wants. */
export const slabSDF = (p) => e3tMap(p, MODE.SLAB)[0];
/** The 3-torus's. */
export const cubeSDF = (p) => e3tMap(p, MODE.CUBE)[0];

// --- the same world, as GLSL ---------------------------------------------

const num = (n) => {
  const s = Number(n).toPrecision(9);
  return s.includes('.') || s.includes('e') ? s : `${s}.0`;
};

/**
 * Emit the world for the shader.
 *
 * Written out rather than rolled, for the reason level.js's is: these are
 * constant array reads in the march inner loop and unrolled the compiler folds
 * them. Sixteen primitives of two or three lines each, against the hyperbolic
 * level's 39 of three asinh slabs, so this program should link well under it.
 *
 * `uOpen` picks the world, and it is the SAME uniform the hyperbolic build
 * uses to mean "floor and ceiling removed" -- which here is not a decoration
 * but the gluing: in the 3-torus the roof at z = 3 IS the floor at z = 0, so
 * removing them is exactly what identifying them looks like.
 */
export function e3tGLSL() {
  const w = E3T_WALLS.length, c = E3T_PILLARS.length, r = E3T_RODS.length;
  return `
const vec3 E3T_CELL = vec3(${CELL.map(num).join(', ')});
// mid.xy, half-extent.xy -- the wall's centre segment.
const vec4 E3T_W[${w}] = vec4[${w}](
    ${E3T_WALLS.map((x) => `vec4(${[...x.mid, ...x.ext].map(num).join(', ')})`).join(',\n    ')});
// x = top height, y = material.
const vec2 E3T_WM[${w}] = vec2[${w}](
    ${E3T_WALLS.map((x) => `vec2(${num(x.top)}, ${num(x.mat)})`).join(',\n    ')});
// centre.xy, radius, top.
const vec4 E3T_P[${c}] = vec4[${c}](
    ${E3T_PILLARS.map((x) => `vec4(${[...x.c, x.r, x.top].map(num).join(', ')})`).join(',\n    ')});
const float E3T_PM[${c}] = float[${c}](${E3T_PILLARS.map((x) => num(x.mat)).join(', ')});
// axis, offset in the two OTHER coordinates, radius.
const vec4 E3T_R[${r}] = vec4[${r}](
    ${E3T_RODS.map((x) => `vec4(${[x.axis, ...x.at, x.r].map(num).join(', ')})`).join(',\n    ')});
const float E3T_RM[${r}] = float[${r}](${E3T_RODS.map((x) => num(x.mat)).join(', ')});

// The whole quotient, in one line, and the reason nothing else in this program
// mentions a group. See torusDisp in e3t.js: reduction here is a rounding,
// where in H^3 it is a seven-step greedy search, so the strategy that was
// unaffordable there is the obvious one here.
vec2 wrapXY(vec2 d) { return d - E3T_CELL.xy * round(d / E3T_CELL.xy); }
float wrapZ(float d) { return d - E3T_CELL.z * round(d / E3T_CELL.z); }

vec2 e3tWorld(vec4 p) {
  if (uOpen > 0.5) {
    // The 3-TORUS, and its content is the rods and nothing else -- the same
    // split level.js makes between its octagon-only and dodecahedron-only
    // sets. A rod meets its own image across the faces it runs into, so each
    // of these is one infinite straight rod through every copy of the room.
    vec2 m = vec2(1e9, 6.0);
    for (int i = 0; i < ${r}; i++) {
      int a = int(E3T_R[i].x);
      vec2 q = a == 0 ? p.yz : (a == 1 ? p.xz : p.xy);
      vec2 cell = a == 0 ? E3T_CELL.yz : (a == 1 ? E3T_CELL.xz : E3T_CELL.xy);
      vec2 d = q - E3T_R[i].yz;
      d -= cell * round(d / cell);
      float s = length(d) - E3T_R[i].w;
      if (s < m.x) m = vec2(s, E3T_RM[i]);
    }
    return m;
  }
  // The slab world. Floor and roof are surfaces and their exact distance is
  // the coordinate -- the cheapest exact surface in the project, again.
  vec2 m = vec2(min(p.z, ${num(CEIL_Z)} - p.z),
                p.z < ${num(CEIL_Z)} * 0.5 ? 1.0 : 2.0);
  for (int i = 0; i < ${w}; i++) {
    vec2 d = wrapXY(p.xy - E3T_W[i].xy);
    vec2 e = E3T_W[i].zw;
    float ee = dot(e, e);
    float h = ee > 0.0 ? clamp(dot(d, e) / ee, -1.0, 1.0) : 0.0;
    float s = max(length(d - e * h) - ${num(WALL_T)}, p.z - E3T_WM[i].x);
    if (s < m.x) m = vec2(s, E3T_WM[i].y);
  }
  for (int i = 0; i < ${c}; i++) {
    float s = max(length(wrapXY(p.xy - E3T_P[i].xy)) - E3T_P[i].z,
                  p.z - E3T_P[i].w);
    if (s < m.x) m = vec2(s, E3T_PM[i]);
  }
  return m;
}
`;
}

// --- walking, falling and jumping ----------------------------------------
//
// The same small honest slice s3.js, h2r.js and s2r.js each carry: no rope, no
// boomerang, no portals, no opponent. All of that is built on hyp.js and its
// group top to bottom.
//
// It is also the shortest of the four, because in flat space the integrator IS
// the answer: a geodesic is a straight line, velocity in frame components is
// constant along one because the frame does not rotate at all, and there is no
// `reorthonormalize` drift worth worrying about because coordinates do not
// grow like cosh. Every hard-won correction in physics.js is a no-op here,
// which is exactly what makes this the control.

export const E3T_G = 9.0;
export const E3T_WALK = 2.2;
export const E3T_GRIP = 14.0;
export const E3T_AIR = 3.0;
export const E3T_JUMP = 4.2;         // apex 0.98, hang time 0.93 s
export const E3T_FLY = 3.0;          // free-flight speed in the 3-torus
export const E3T_PLAYER_R = 0.10;

/** Standing on something? Measured against the world, not against z alone. */
export const grounded = (M, sdf, r = E3T_PLAYER_R) => sdf(point(M)) <= r + 1e-3;

/**
 * Steer horizontally and fall vertically, in frame components.
 *
 * Identical in shape to `s2rControl`, and that is the claim: the control law
 * does not know what curvature it is in, because a product's factors do not
 * interact and flat space is the product where NEITHER factor is curved.
 */
export function e3tControl(v, want, onGround, dt, g = E3T_G) {
  const rate = onGround ? E3T_GRIP : E3T_AIR;
  const k = 1 - Math.exp(-rate * dt);
  return [
    v[0] + (want[0] * E3T_WALK - v[0]) * k,
    v[1] + (want[1] * E3T_WALK - v[1]) * k,
    v[2] - g * dt,
  ];
}

export const E3T_THRUST = E3T_FLY * 6.0;   // the flight damping, as an accel

/**
 * Free flight in the 3-torus: all three axes, steered along the view.
 *
 * WITH GRAVITY ON THE VERTICAL MUST NOT BE DAMPED, and getting that wrong is
 * not a tuning matter -- it deletes the one thing this world is here to show.
 * Steering toward a target speed is a first-order lag, so adding a constant
 * `-g dt` to it gives a TERMINAL VELOCITY of g/rate: measured, 1.50 against
 * the 7.35 an honest cell of free fall gives, and every lap identical. The
 * endless fall silently became a lift descending at walking pace.
 *
 * So with gravity on the vertical takes a thrust and gravity and NOTHING takes
 * speed away, which is what "the force descends and the potential does not"
 * has to feel like: you fall through the floor, arrive through the roof, and
 * arrive faster than you left, for ever.
 */
export function e3tFly(v, want, dt, g = 0) {
  const k = 1 - Math.exp(-6.0 * dt);
  return [
    v[0] + (want[0] * E3T_FLY - v[0]) * k,
    v[1] + (want[1] * E3T_FLY - v[1]) * k,
    g === 0
      ? v[2] + (want[2] * E3T_FLY - v[2]) * k
      : v[2] + want[2] * E3T_THRUST * dt - g * dt,
  ];
}

/**
 * Advance one substep along the geodesic the velocity points down.
 *
 * The same shape as `stepFree`, `s3Step`, `stepFall` and `s2rStep`, and here
 * it really is just `p += v dt` -- `geom.js` at k = 0 composes an affine
 * translation and nothing is approximated.
 */
export function e3tStep(M, v, dt, mode = null) {
  const speed = Math.hypot(v[0], v[1], v[2]);
  const moved = speed < 1e-12 ? M : geodesic(M, [v[0] / speed, v[1] / speed, v[2] / speed],
    speed * dt);
  return [reorthonormalize(mode ? foldPlacement(moved, mode) : moved), v];
}

/**
 * Bring a placement's POINT back into the cell, leaving its frame alone.
 *
 * The renderer does not need this -- `hDist` folds every displacement, so an
 * unfolded centre still draws in the right place. What needs it is FLOAT32.
 * Nothing folds the player otherwise, so a long session walks out to
 * coordinates of a few hundred, and the shader then computes small
 * differences between large numbers: at x = 1e5 the float32 spacing is 0.008,
 * which is visible. This is `settleCarried` in physics.js making the same
 * argument, and it is much cheaper here because the correction is a lattice
 * vector rather than a group element and the frame is untouched by it.
 *
 * Safe to do at any moment, and that is not obvious: it moves the player a
 * whole cell in coordinates. It works because every other question here --
 * the crossing test, the gate overlay, the collision, the distance to
 * anything -- is asked through `torusDisp`, which cannot tell the difference.
 */
export function foldPlacement(M, mode) {
  const g = foldElement(point(M), mode);
  if (!g[0] && !g[1] && !g[2]) return M;
  const out = M.slice();
  out[12] -= g[0]; out[13] -= g[1]; out[14] -= g[2];
  return out;
}

/** The outward normal of the surface at the player, in frame components. */
export function surfaceNormal(M, sdf) {
  const e = 1e-4;
  const g = [0, 0, 0];
  for (let i = 0; i < 3; i++) {
    const d = [0, 0, 0];
    d[i] = 1;
    g[i] = (sdf(rayPoint(M, d, e)) - sdf(rayPoint(M, d, -e))) / (2 * e);
  }
  const m = Math.hypot(g[0], g[1], g[2]);
  if (m < 1e-12) return [0, 0, 1];
  return [g[0] / m, g[1] / m, g[2] / m];
}

/** Push out of anything the player is inside, and kill the velocity going in. */
export function e3tCollide(M, v, sdf, r = E3T_PLAYER_R) {
  let normal = null;
  for (let i = 0; i < 4; i++) {
    const d = sdf(point(M)) - r;
    if (d >= 0) break;
    const n = surfaceNormal(M, sdf);
    M = geodesic(M, n, -d);
    normal = n;
    const vn = v[0] * n[0] + v[1] * n[1] + v[2] * n[2];
    if (vn < 0) v = [v[0] - vn * n[0], v[1] - vn * n[1], v[2] - vn * n[2]];
  }
  return [reorthonormalize(M), v, normal];
}

/** A jump: set the vertical component, do not add to it. */
export const jump = (v) => [v[0], v[1], E3T_JUMP];

// --- GRAVITY WITHOUT A HEIGHT, which is the 3-torus's alone ---------------
//
// CLAUDE.md states the rule that governs every world here: gravity has to be
// the gradient of a function with |grad| = 1, and that function has to be
// invariant under the group or it does not descend to the quotient. Both
// hyperbolic worlds are decided by it -- the plane field survives the octagon
// group because its generators lie in the floor plane; nothing survives the
// dodecahedral one, so the open world has no down and cannot have one.
//
// The 3-torus splits that rule down the middle, and it is the only world here
// that can:
//
//     the FORCE descends.       d/dz is invariant under every lattice
//                               translation, so "down" is a perfectly good
//                               constant vector field on T^3.
//     the POTENTIAL does not.   z is not periodic, so there is no height
//                               function on T^3 at all -- and by the same
//                               argument there cannot be, since a continuous
//                               function on a compact manifold has a maximum
//                               and a maximum has no gradient.
//
// What that IS, played: you fall through the floor, arrive through the roof,
// and arrive FASTER THAN YOU LEFT. There is no terminal state and no
// conservation of energy, because energy is only defined once you name a lift
// and the lift changes every lap. An endless fall inside a finite room.
//
// Nothing else in this project does this. In the octagon world the field has a
// potential and confines you. In the open world there is no field. In both
// products the height is an honest Euclidean line with an honest potential and
// a floor at the bottom of it. Here the force is real, invariant and
// integrable, and it has no potential whatsoever.
//
// `e3t.test.js` measures the speed gained per lap, which is exactly
// sqrt(2 g Lz) worth of energy per lap and grows without bound.

/**
 * One lap's worth of falling, from a standstill, as the speed on return.
 *
 * Its own function because it is the measurement rather than a mechanic:
 * having fallen the cell height under constant g, you are back where you
 * started with sqrt(v^2 + 2 g Lz) instead of v.
 */
export const fallLap = (v, g = E3T_G) => Math.sqrt(v * v + 2 * g * CELL[2]);

// --- the hoop course ------------------------------------------------------
//
// Hoops along a CLOSED GEODESIC, so flying dead straight takes every one and
// returns you to where you began -- which is word for word what the bounded
// world's course does, and the mechanism could hardly be more different. There
// it is one of eight rigid axes fixed by the group, and the course has to move
// the player onto it because a geodesic parallel to a generator's axis but
// offset from it does not close. Here EVERY parallel translate closes, so the
// course can be laid wherever there is room and the player can join it
// anywhere along its length.
//
// The direction is (1, 1, 1) -- the cell diagonal, which wraps exactly once in
// each axis and shuts after L*sqrt(3) = 5.196, a flight nearly twice as long
// as the room is wide. The vertical component is what makes it a genuine 3D
// course, and it is also what pins it to the 3-TORUS: in the slab world z is
// not glued, so a geodesic with any rise never comes back. The preset says so
// and the option lock enforces it.
//
// Compare the hyperbolic pair, which are forced the other way round and for a
// much deeper reason: EVERY generator of the octagon group is a translation
// along an axis lying IN the floor plane, so every closed geodesic in the
// bounded world lies in it too -- all six hoops at altitude 0.0000, a
// floor-level slalom, and no aim can change that. Here the flat course is 3D
// by construction and the flat FLOOR world simply has no closed geodesic with
// any rise at all.

export const HOOP_R = 0.55;
export const HOOP_DIR = [1, 1, 1];
export const HOOPS = 4;

/**
 * A gate is a plane crossed the right way, exactly as the hyperbolic hoops
 * are, and the test is the flat one: the sign of the dot with the normal.
 *
 * The segment's two ends must be compared in the SAME chart, which in a flat
 * torus means the same lift -- so the displacement is taken with `torusDisp`
 * against the gate, never as a raw coordinate difference. That is the flat
 * spelling of "the crossing test must ride on a segment whose ends are in the
 * same chart", and getting it wrong here has the same symptom it does there: a
 * flight right across the room at every wrap, crediting every gate at once.
 */
export function hoopCrossed(p0, p1, gate) {
  const d0 = torusDisp(p0, gate.at, MODE.CUBE);
  // WRAP THE STEP, not the far end. Folding p1 against the gate independently
  // lets a substep that happens to straddle a half-cell boundary come back as
  // a jump of a whole cell, which is a spurious sign change and a gate
  // credited from nowhere. A substep is a few centimetres and its own wrap is
  // unambiguous, so carrying d0 forward by it keeps both ends in one chart --
  // the flat spelling of the rule the hyperbolic course states as 'the
  // crossing test must ride on a segment whose ends are in the SAME chart'.
  const step = torusDisp(p1, p0, MODE.CUBE);
  const d1 = [d0[0] + step[0], d0[1] + step[1], d0[2] + step[2]];
  const s0 = d0[0] * gate.N[0] + d0[1] * gate.N[1] + d0[2] * gate.N[2];
  const s1 = d1[0] * gate.N[0] + d1[1] * gate.N[1] + d1[2] * gate.N[2];
  if (!(s0 < 0 && s1 >= 0)) return false;
  // Where it crossed, and whether that was inside the ring.
  const f = s0 === s1 ? 0 : s0 / (s0 - s1);
  const hit = [0, 1, 2].map((i) => d0[i] + (d1[i] - d0[i]) * f);
  return Math.hypot(hit[0], hit[1], hit[2]) <= gate.r;
}

/** The course: `n` gates evenly spaced along the closed (2,1,1) geodesic. */
export function hoopCourse(n = HOOPS) {
  const len = closedLength(...HOOP_DIR);
  const v = [HOOP_DIR[0] * CELL[0], HOOP_DIR[1] * CELL[1], HOOP_DIR[2] * CELL[2]];
  const N = v.map((x) => x / len);
  const hoops = [];
  for (let i = 0; i < n; i++) {
    // Offset by half a spacing so no gate sits on the start line.
    const s = (i + 0.5) * len / n;
    hoops.push({ at: [N[0] * s, N[1] * s, N[2] * s, 1], N, r: HOOP_R, s });
  }
  return { kind: 'e3t-hoops', len, hoops, crossed: hoopCrossed };
}

/**
 * The copy of a point nearest a viewer, which a LINE OVERLAY needs and the
 * marcher does not.
 *
 * `hoopNear` in hyp.js exists for exactly this and the argument is the same
 * one, arriving from the other direction. There, the marcher's view teleports
 * at every face and the overlay does not, so a hoop named a cell away projects
 * to the wrong part of the screen. Here the marcher does not teleport at all
 * -- it runs straight out into the covering space -- but `hDist` folds every
 * displacement, so what it DRAWS at a coordinate is that coordinate's nearest
 * image. A gate 5.2 units down the diagonal is drawn wherever its nearest copy
 * is, which is not down the diagonal, and an overlay at the literal coordinate
 * would sit somewhere else entirely.
 *
 * Two different mechanisms, one symptom, one fix.
 */
export function nearImage(q, from, mode = MODE.CUBE) {
  const d = torusDisp(q, from, mode);
  return [from[0] + d[0], from[1] + d[1], from[2] + d[2], 1];
}

/**
 * The gate's ring, for main.js to draw as a line loop.
 *
 * Drawn as line loops rather than as shader primitives, like every other
 * course in this project: a curve in `sceneMap` is inlined three times and
 * paid for at link time, which is the budget that binds.
 */
export function gateRing(gate, n = 40, from = null) {
  const at = from ? nearImage(gate.at, from) : gate.at;
  const N = gate.N;
  // Any unit vector not along N, then two perpendiculars.
  const seed = Math.abs(N[0]) < 0.9 ? [1, 0, 0] : [0, 1, 0];
  const c = seed[0] * N[0] + seed[1] * N[1] + seed[2] * N[2];
  let a = [seed[0] - c * N[0], seed[1] - c * N[1], seed[2] - c * N[2]];
  const m = Math.hypot(a[0], a[1], a[2]);
  a = [a[0] / m, a[1] / m, a[2] / m];
  const b = [N[1] * a[2] - N[2] * a[1], N[2] * a[0] - N[0] * a[2], N[0] * a[1] - N[1] * a[0]];
  const out = [];
  for (let i = 0; i < n; i++) {
    const th = 2 * Math.PI * i / n;
    const cs = Math.cos(th) * gate.r, sn = Math.sin(th) * gate.r;
    out.push([at[0] + a[0] * cs + b[0] * sn,
              at[1] + a[1] * cs + b[1] * sn,
              at[2] + a[2] * cs + b[2] * sn, 1]);
  }
  return out;
}

/** The course's unit direction, in world components and in frame ones alike. */
export function hoopDir() {
  const len = closedLength(...HOOP_DIR);
  return [HOOP_DIR[0] * CELL[0] / len, HOOP_DIR[1] * CELL[1] / len,
          HOOP_DIR[2] * CELL[2] / len];
}

/**
 * Where a run starts: at the origin, ON the course line, already looking down
 * it -- so "fly dead straight from here" is the whole course.
 *
 * The frame is the identity, so frame components and world components are the
 * same thing and the camera angles come straight off the direction. The
 * hyperbolic course cannot do this: its hoops have to lie on the axis through
 * the CELL CENTRE, because a geodesic parallel to a generator's axis but
 * offset from it does not close up, so `beginRun` moves the player onto the
 * course. Here every parallel translate closes, so the course could be laid
 * anywhere and the player could join it anywhere along its length.
 */
export function hoopStart() {
  const d = hoopDir();
  return {
    M: IDENTITY.slice(),
    yaw: Math.atan2(d[1], d[0]),
    pitch: Math.asin(Math.max(-1, Math.min(1, d[2]))),
  };
}

/**
 * Where the slab world starts: in the street, on the clear centreline.
 *
 * Nothing at the spawn, for the reason CLAUDE.md gives: a camera inside
 * geometry makes every ray hit at t = 0 and fills the screen with one flat
 * colour, which looks exactly like a shader that failed to compile.
 */
export const slabStart = () => placeAt(-0.55, 0, E3T_PLAYER_R + 0.5);

/**
 * Where the 3-torus starts: the cell centre, which is on the course line and
 * which every rod is at least 0.571 clear of -- searched for, and asserted.
 */
export const cubeStart = () => IDENTITY.slice();
